### ISSUE TITLE
Unexpected disconnection

### ISSUE THREAD

**Issue by Herr-chirurg** [Maxentr/Skyjo#42]
Hi it's us again !
Skyjo is our only salvation for passing time during a boring apache class (there is no more work to do, juste preparing for the exam).

**Describe the bug**
Unexpected disconnection with **5 players games**

**To Reproduce**
We started 3 5-players games within the two the last week, we encountered this bug 3 time already, always in the two first rounds.

**Priority**
Unfortunately, this bug prevent us to finish a game.

Desktop
OS: Windows
Browser : Chrome, Firefox

**Comment by Maxentr** [comment]
Hello,
Thanks for playing on my website! I'm currently updating the server to store games in a PostgreSQL database instead of in memory. This change will allow me to improve disconnection management by implementing a 30-second window for players to reconnect. Please note that I'm currently using a free server, so performance may not be as good as I'd like. If you have any suggestions for improvement, I'd love to hear them.

**Comment by Herr-chirurg** [comment]
Hello,
A PostgreSQL database sounds good ! 
I'm sure it will be a big improvement for performance.

I didn't know you used a free server, i understand better the performances issues. 
I don't have enough experience to judge a good server, but a friend advised me a VPS from onetsolutions.net.

I think i pay it 2 or 5€ a month ? For 8 gb ? Don't really remember, and i can't check as my proxy is blocking it. 
But i run a terraria server on it, for 2 to 3 players. It get the job done, and never had an issue.

**Comment by Maxentr** [comment]
Thank you for the suggestion and for understanding the current situation! The switch to PostgreSQL will let us store games persistently, ensuring that if the server doesn't have a game in memory or restarts unexpectedly, we can still retrieve it without losing progress. The update should be live today (10/08) or tomorrow.

As for the server, I appreciate the recommendation. For now, I'm sticking with the free server since our player base is still small, and I don't want to invest money into it just yet. However, if the player count continues to grow, and we need better performance, I'll definitely consider options like the VPS you mentioned.
